# This is a sample build configuration for C++ – Make.
# Check our guides at https://confluence.atlassian.com/x/5Q4SMw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: gcc:6.5

pipelines:
  default:
  - parallel:
      - step:
        name: Build on root-centos
        image: rootproject/root-centos
        script: # Modify the commands below to build your repository.
          - #./configure
          - gcc -v
          - git clone https://bitbucket.org/tmidas/mxml.git
          - make MXML_DIR=./mxml
          - #make test
     - step:
        name: cmake build on root-centos
        image: rootproject/root-centos
        script: # Modify the commands below to build your repository.
          - gcc -v
          - git clone https://bitbucket.org/tmidas/mxml.git
          - make cmake3
