# This is a sample build configuration for C++ – Make.
# Check our guides at https://confluence.atlassian.com/x/5Q4SMw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: gcc:6.5

pipelines:
  default:
  - parallel:
    - step:
        name: Build on root-centos
        image: rootproject/root-centos
        script:
          - gcc -v
          - which root-config
          - root-config --version
          - root-config --cflags
          - root-config --features
          - git submodule update --init
          - make

    - step:
        name: Build on root-centos with cmake
        image: rootproject/root-centos
        script:
          - gcc -v
          - which root-config
          - root-config --version
          - root-config --cflags
          - root-config --features
          - git submodule update --init
          - make cmake3

#    - step:
#        name: Build on el6 CERN SLC6
#        #image: cern/slc6-base # no gcc
#        image: centos:centos6
#        script:
#          - gcc -v
#          - git clone https://bitbucket.org/tmidas/mxml.git
#          - git clone https://bitbucket.org/tmidas/mscb.git
#          - make

